-- =================================================================
-- HRIS Database - Oracle 23c Free Edition
-- CREATE TABLE Scripts
-- =================================================================
-- Author: Generated for ICT502 Group Project
-- Date: January 17, 2026
-- Description: Complete database schema for Human Resources Information System
-- =================================================================

-- Drop existing tables if they exist (in reverse order of dependencies)
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE PAYROLL CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE PERFORMANCE_EVALUATION CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE LEAVE CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE LEAVE_TYPE CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE ATTENDANCE CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE EMPLOYEE_QUALIFICATION CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE CONTRACT_EMPLOYEE CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE PERMANENT_EMPLOYEE CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE EMPLOYEE CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE QUALIFICATION CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE POSITION CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE DEPARTMENT CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      NULL; -- Ignore errors if tables don't exist
END;
/

-- =================================================================
-- 1. DEPARTMENT TABLE
-- =================================================================
CREATE TABLE DEPARTMENT (
    department_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    department_name VARCHAR2(100) NOT NULL,
    location VARCHAR2(150),
    budget NUMBER(15,2),
    manager_id NUMBER,  -- FK to EMPLOYEE (added later via ALTER TABLE)
    created_date DATE DEFAULT SYSDATE,
    CONSTRAINT uq_department_name UNIQUE (department_name)
);

COMMENT ON TABLE DEPARTMENT IS 'Stores department information including budget and location';
COMMENT ON COLUMN DEPARTMENT.department_id IS 'Primary key, auto-increment';
COMMENT ON COLUMN DEPARTMENT.department_name IS 'Department name (unique)';
COMMENT ON COLUMN DEPARTMENT.location IS 'Physical location of department';
COMMENT ON COLUMN DEPARTMENT.budget IS 'Department annual budget';
COMMENT ON COLUMN DEPARTMENT.manager_id IS 'Foreign key to EMPLOYEE table (department manager)';

-- =================================================================
-- 2. POSITION TABLE
-- =================================================================
CREATE TABLE POSITION (
    position_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    position_title VARCHAR2(100) NOT NULL,
    job_description VARCHAR2(1000),
    min_salary NUMBER(10,2) NOT NULL,
    max_salary NUMBER(10,2) NOT NULL,
    created_date DATE DEFAULT SYSDATE,
    CONSTRAINT uq_position_title UNIQUE (position_title),
    CONSTRAINT chk_salary_range CHECK (max_salary > min_salary),
    CONSTRAINT chk_min_salary_positive CHECK (min_salary > 0)
);

COMMENT ON TABLE POSITION IS 'Stores job position information and salary ranges';
COMMENT ON COLUMN POSITION.position_id IS 'Primary key, auto-increment';
COMMENT ON COLUMN POSITION.position_title IS 'Job title (unique)';
COMMENT ON COLUMN POSITION.job_description IS 'Detailed job description and responsibilities';
COMMENT ON COLUMN POSITION.min_salary IS 'Minimum salary for this position';
COMMENT ON COLUMN POSITION.max_salary IS 'Maximum salary for this position';

-- =================================================================
-- 3. EMPLOYEE TABLE (Supertype)
-- =================================================================
CREATE TABLE EMPLOYEE (
    employee_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    email VARCHAR2(100) NOT NULL,
    phone_number VARCHAR2(20),
    date_of_birth DATE,
    hire_date DATE DEFAULT SYSDATE NOT NULL,
    address VARCHAR2(250),
    supervisor_id NUMBER,  -- FK to EMPLOYEE (recursive, added later via ALTER TABLE)
    department_id NUMBER NOT NULL,  -- FK to DEPARTMENT (added later via ALTER TABLE)
    position_id NUMBER NOT NULL,  -- FK to POSITION (added later via ALTER TABLE)
    employment_type VARCHAR2(20) NOT NULL,  -- 'CONTRACT' or 'PERMANENT'
    status VARCHAR2(20) DEFAULT 'ACTIVE',  -- 'ACTIVE', 'INACTIVE', 'TERMINATED'
    created_date DATE DEFAULT SYSDATE,
    last_modified_date DATE DEFAULT SYSDATE,
    CONSTRAINT uq_employee_email UNIQUE (email),
    CONSTRAINT chk_employment_type CHECK (employment_type IN ('CONTRACT', 'PERMANENT')),
    CONSTRAINT chk_employee_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'TERMINATED'))
);

COMMENT ON TABLE EMPLOYEE IS 'Supertype table storing common employee information';
COMMENT ON COLUMN EMPLOYEE.employee_id IS 'Primary key, auto-increment';
COMMENT ON COLUMN EMPLOYEE.email IS 'Employee email (unique)';
COMMENT ON COLUMN EMPLOYEE.date_of_birth IS 'Employee date of birth';
COMMENT ON COLUMN EMPLOYEE.address IS 'Employee residential address';
COMMENT ON COLUMN EMPLOYEE.supervisor_id IS 'Foreign key to EMPLOYEE (recursive relationship)';
COMMENT ON COLUMN EMPLOYEE.employment_type IS 'Type of employment: CONTRACT or PERMANENT';
COMMENT ON COLUMN EMPLOYEE.status IS 'Current employment status';

-- =================================================================
-- 4. CONTRACT_EMPLOYEE TABLE (Subtype)
-- =================================================================
CREATE TABLE CONTRACT_EMPLOYEE (
    employee_id NUMBER PRIMARY KEY,  -- PK and FK to EMPLOYEE (added later via ALTER TABLE)
    hourly_rate NUMBER(8,2) NOT NULL,
    contract_start_date DATE DEFAULT SYSDATE NOT NULL,
    contract_end_date DATE NOT NULL,
    created_date DATE DEFAULT SYSDATE,
    CONSTRAINT chk_hourly_rate_positive CHECK (hourly_rate > 0),
    CONSTRAINT chk_contract_dates CHECK (contract_end_date > contract_start_date)
);

COMMENT ON TABLE CONTRACT_EMPLOYEE IS 'Subtype table for contract employees';
COMMENT ON COLUMN CONTRACT_EMPLOYEE.employee_id IS 'Primary key and foreign key to EMPLOYEE';
COMMENT ON COLUMN CONTRACT_EMPLOYEE.hourly_rate IS 'Hourly payment rate';
COMMENT ON COLUMN CONTRACT_EMPLOYEE.contract_start_date IS 'Contract start date';
COMMENT ON COLUMN CONTRACT_EMPLOYEE.contract_end_date IS 'Contract expiration date';

-- =================================================================
-- 5. PERMANENT_EMPLOYEE TABLE (Subtype)
-- =================================================================
CREATE TABLE PERMANENT_EMPLOYEE (
    employee_id NUMBER PRIMARY KEY,  -- PK and FK to EMPLOYEE (added later via ALTER TABLE)
    annual_salary NUMBER(10,2) NOT NULL,
    vacation_days NUMBER(3) DEFAULT 20,
    created_date DATE DEFAULT SYSDATE,
    CONSTRAINT chk_annual_salary_positive CHECK (annual_salary > 0),
    CONSTRAINT chk_vacation_days_valid CHECK (vacation_days >= 0 AND vacation_days <= 365)
);

COMMENT ON TABLE PERMANENT_EMPLOYEE IS 'Subtype table for permanent employees';
COMMENT ON COLUMN PERMANENT_EMPLOYEE.employee_id IS 'Primary key and foreign key to EMPLOYEE';
COMMENT ON COLUMN PERMANENT_EMPLOYEE.annual_salary IS 'Annual salary amount';
COMMENT ON COLUMN PERMANENT_EMPLOYEE.vacation_days IS 'Annual vacation days allowance';

-- =================================================================
-- 6. QUALIFICATION TABLE
-- =================================================================
CREATE TABLE QUALIFICATION (
    qualification_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR2(150) NOT NULL,
    description VARCHAR2(500),
    created_date DATE DEFAULT SYSDATE,
    CONSTRAINT uq_qualification_name UNIQUE (name)
);

COMMENT ON TABLE QUALIFICATION IS 'Stores qualification types (degrees, certifications, etc.)';
COMMENT ON COLUMN QUALIFICATION.qualification_id IS 'Primary key, auto-increment';
COMMENT ON COLUMN QUALIFICATION.name IS 'Qualification name (unique)';
COMMENT ON COLUMN QUALIFICATION.description IS 'Detailed description of the qualification';

-- =================================================================
-- 7. EMPLOYEE_QUALIFICATION TABLE (Bridge/Junction Table)
-- =================================================================
CREATE TABLE EMPLOYEE_QUALIFICATION (
    employee_id NUMBER NOT NULL,  -- FK to EMPLOYEE (added later via ALTER TABLE)
    qualification_id NUMBER NOT NULL,  -- FK to QUALIFICATION (added later via ALTER TABLE)
    date_obtained DATE NOT NULL,
    institution_name VARCHAR2(200),
    created_date DATE DEFAULT SYSDATE,
    CONSTRAINT pk_employee_qualification PRIMARY KEY (employee_id, qualification_id)
);

COMMENT ON TABLE EMPLOYEE_QUALIFICATION IS 'Many-to-many relationship between employees and qualifications';
COMMENT ON COLUMN EMPLOYEE_QUALIFICATION.date_obtained IS 'Date when qualification was obtained';
COMMENT ON COLUMN EMPLOYEE_QUALIFICATION.institution_name IS 'Institution that issued the qualification';

-- =================================================================
-- 8. ATTENDANCE TABLE
-- =================================================================
CREATE TABLE ATTENDANCE (
    attendance_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    employee_id NUMBER NOT NULL,  -- FK to EMPLOYEE (added later via ALTER TABLE)
    attendance_date DATE DEFAULT SYSDATE NOT NULL,
    check_in_time TIMESTAMP,
    check_out_time TIMESTAMP,
    remarks VARCHAR2(500),
    created_date DATE DEFAULT SYSDATE,
    last_modified_date DATE DEFAULT SYSDATE
);

COMMENT ON TABLE ATTENDANCE IS 'Stores daily employee attendance records';
COMMENT ON COLUMN ATTENDANCE.attendance_id IS 'Primary key, auto-increment';
COMMENT ON COLUMN ATTENDANCE.employee_id IS 'Foreign key to EMPLOYEE table';
COMMENT ON COLUMN ATTENDANCE.attendance_date IS 'Date of attendance';
COMMENT ON COLUMN ATTENDANCE.check_in_time IS 'Check-in timestamp';
COMMENT ON COLUMN ATTENDANCE.check_out_time IS 'Check-out timestamp';
COMMENT ON COLUMN ATTENDANCE.remarks IS 'Additional notes or remarks';

-- =================================================================
-- 9. LEAVE_TYPE TABLE
-- =================================================================
CREATE TABLE LEAVE_TYPE (
    leave_type_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    type_name VARCHAR2(50) NOT NULL,
    description VARCHAR2(500),
    created_date DATE DEFAULT SYSDATE,
    CONSTRAINT uq_leave_type_name UNIQUE (type_name)
);

COMMENT ON TABLE LEAVE_TYPE IS 'Stores different types of leave (Sick, Vacation, etc.)';
COMMENT ON COLUMN LEAVE_TYPE.leave_type_id IS 'Primary key, auto-increment';
COMMENT ON COLUMN LEAVE_TYPE.type_name IS 'Name of leave type (unique)';
COMMENT ON COLUMN LEAVE_TYPE.description IS 'Description of leave type';

-- =================================================================
-- 10. LEAVE TABLE
-- =================================================================
CREATE TABLE LEAVE (
    leave_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    employee_id NUMBER NOT NULL,  -- FK to EMPLOYEE (added later via ALTER TABLE)
    leave_type_id NUMBER NOT NULL,  -- FK to LEAVE_TYPE (added later via ALTER TABLE)
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    reason VARCHAR2(1000),
    application_date DATE DEFAULT SYSDATE NOT NULL,
    leave_status VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,  -- 'PENDING', 'APPROVED', 'REJECTED'
    approved_by NUMBER,  -- FK to EMPLOYEE (manager/supervisor who approved)
    approval_date DATE,
    created_date DATE DEFAULT SYSDATE,
    last_modified_date DATE DEFAULT SYSDATE,
    CONSTRAINT chk_leave_dates CHECK (end_date >= start_date),
    CONSTRAINT chk_leave_status CHECK (leave_status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED'))
);

COMMENT ON TABLE LEAVE IS 'Stores employee leave applications and approvals';
COMMENT ON COLUMN LEAVE.leave_id IS 'Primary key, auto-increment';
COMMENT ON COLUMN LEAVE.employee_id IS 'Foreign key to EMPLOYEE (applicant)';
COMMENT ON COLUMN LEAVE.leave_type_id IS 'Foreign key to LEAVE_TYPE';
COMMENT ON COLUMN LEAVE.start_date IS 'Leave start date';
COMMENT ON COLUMN LEAVE.end_date IS 'Leave end date';
COMMENT ON COLUMN LEAVE.application_date IS 'Date when leave was applied';
COMMENT ON COLUMN LEAVE.leave_status IS 'Status: PENDING, APPROVED, REJECTED, CANCELLED';
COMMENT ON COLUMN LEAVE.approved_by IS 'Foreign key to EMPLOYEE (approver/manager)';

-- =================================================================
-- 11. PERFORMANCE_EVALUATION TABLE
-- =================================================================
CREATE TABLE PERFORMANCE_EVALUATION (
    evaluation_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    employee_id NUMBER NOT NULL,  -- FK to EMPLOYEE (subject being evaluated)
    evaluator_id NUMBER NOT NULL,  -- FK to EMPLOYEE (manager/evaluator)
    evaluation_date DATE DEFAULT SYSDATE NOT NULL,
    score NUMBER(5,2),
    status VARCHAR2(20) DEFAULT 'DRAFT',  -- 'DRAFT', 'COMPLETED', 'REVIEWED'
    strengths CLOB,
    weaknesses CLOB,
    goals VARCHAR2(2000),
    created_date DATE DEFAULT SYSDATE,
    last_modified_date DATE DEFAULT SYSDATE,
    CONSTRAINT chk_eval_score CHECK (score >= 0 AND score <= 100),
    CONSTRAINT chk_eval_status CHECK (status IN ('DRAFT', 'COMPLETED', 'REVIEWED', 'APPROVED'))
);

COMMENT ON TABLE PERFORMANCE_EVALUATION IS 'Stores employee performance evaluation records';
COMMENT ON COLUMN PERFORMANCE_EVALUATION.evaluation_id IS 'Primary key, auto-increment';
COMMENT ON COLUMN PERFORMANCE_EVALUATION.employee_id IS 'Foreign key to EMPLOYEE (subject being evaluated)';
COMMENT ON COLUMN PERFORMANCE_EVALUATION.evaluator_id IS 'Foreign key to EMPLOYEE (manager conducting evaluation)';
COMMENT ON COLUMN PERFORMANCE_EVALUATION.evaluation_date IS 'Date of evaluation';
COMMENT ON COLUMN PERFORMANCE_EVALUATION.score IS 'Performance score (0-100)';
COMMENT ON COLUMN PERFORMANCE_EVALUATION.strengths IS 'Employee strengths (CLOB for large text)';
COMMENT ON COLUMN PERFORMANCE_EVALUATION.weaknesses IS 'Areas for improvement (CLOB for large text)';
COMMENT ON COLUMN PERFORMANCE_EVALUATION.goals IS 'Goals and objectives for next period';

-- =================================================================
-- 12. PAYROLL TABLE
-- =================================================================
CREATE TABLE PAYROLL (
    payroll_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    employee_id NUMBER NOT NULL,  -- FK to EMPLOYEE (added later via ALTER TABLE)
    pay_period_start DATE NOT NULL,
    pay_period_end DATE NOT NULL,
    payment_date DATE NOT NULL,
    gross_pay NUMBER(12,2) NOT NULL,
    allowances NUMBER(10,2) DEFAULT 0,
    overtime_pay NUMBER(10,2) DEFAULT 0,
    deductions NUMBER(10,2) DEFAULT 0,
    tax_amount NUMBER(10,2) DEFAULT 0,
    net_pay NUMBER(12,2) NOT NULL,
    payment_method VARCHAR2(30) DEFAULT 'BANK_TRANSFER',
    created_date DATE DEFAULT SYSDATE,
    last_modified_date DATE DEFAULT SYSDATE,
    CONSTRAINT chk_pay_period CHECK (pay_period_end > pay_period_start),
    CONSTRAINT chk_gross_pay_positive CHECK (gross_pay >= 0),
    CONSTRAINT chk_net_pay_positive CHECK (net_pay >= 0),
    CONSTRAINT chk_payment_method CHECK (payment_method IN ('BANK_TRANSFER', 'CHEQUE', 'CASH', 'DIRECT_DEPOSIT'))
);

COMMENT ON TABLE PAYROLL IS 'Stores employee payroll and payment records';
COMMENT ON COLUMN PAYROLL.payroll_id IS 'Primary key, auto-increment';
COMMENT ON COLUMN PAYROLL.employee_id IS 'Foreign key to EMPLOYEE';
COMMENT ON COLUMN PAYROLL.pay_period_start IS 'Start date of pay period';
COMMENT ON COLUMN PAYROLL.pay_period_end IS 'End date of pay period';
COMMENT ON COLUMN PAYROLL.payment_date IS 'Actual payment date';
COMMENT ON COLUMN PAYROLL.gross_pay IS 'Gross salary before deductions';
COMMENT ON COLUMN PAYROLL.allowances IS 'Additional allowances';
COMMENT ON COLUMN PAYROLL.overtime_pay IS 'Overtime payment';
COMMENT ON COLUMN PAYROLL.deductions IS 'Total deductions';
COMMENT ON COLUMN PAYROLL.tax_amount IS 'Tax amount';
COMMENT ON COLUMN PAYROLL.net_pay IS 'Net salary after all deductions';
COMMENT ON COLUMN PAYROLL.payment_method IS 'Method of payment';

-- =================================================================
-- FOREIGN KEY CONSTRAINTS (Added at the end to avoid circular dependencies)
-- =================================================================

-- DEPARTMENT foreign keys
ALTER TABLE DEPARTMENT
    ADD CONSTRAINT fk_dept_manager 
    FOREIGN KEY (manager_id) 
    REFERENCES EMPLOYEE(employee_id)
    ON DELETE SET NULL;

-- EMPLOYEE foreign keys
ALTER TABLE EMPLOYEE
    ADD CONSTRAINT fk_emp_supervisor 
    FOREIGN KEY (supervisor_id) 
    REFERENCES EMPLOYEE(employee_id)
    ON DELETE SET NULL;

ALTER TABLE EMPLOYEE
    ADD CONSTRAINT fk_emp_department 
    FOREIGN KEY (department_id) 
    REFERENCES DEPARTMENT(department_id)
    ON DELETE CASCADE;

ALTER TABLE EMPLOYEE
    ADD CONSTRAINT fk_emp_position 
    FOREIGN KEY (position_id) 
    REFERENCES POSITION(position_id)
    ON DELETE CASCADE;

-- CONTRACT_EMPLOYEE foreign key
ALTER TABLE CONTRACT_EMPLOYEE
    ADD CONSTRAINT fk_contract_employee 
    FOREIGN KEY (employee_id) 
    REFERENCES EMPLOYEE(employee_id)
    ON DELETE CASCADE;

-- PERMANENT_EMPLOYEE foreign key
ALTER TABLE PERMANENT_EMPLOYEE
    ADD CONSTRAINT fk_permanent_employee 
    FOREIGN KEY (employee_id) 
    REFERENCES EMPLOYEE(employee_id)
    ON DELETE CASCADE;

-- EMPLOYEE_QUALIFICATION foreign keys
ALTER TABLE EMPLOYEE_QUALIFICATION
    ADD CONSTRAINT fk_emp_qual_employee 
    FOREIGN KEY (employee_id) 
    REFERENCES EMPLOYEE(employee_id)
    ON DELETE CASCADE;

ALTER TABLE EMPLOYEE_QUALIFICATION
    ADD CONSTRAINT fk_emp_qual_qualification 
    FOREIGN KEY (qualification_id) 
    REFERENCES QUALIFICATION(qualification_id)
    ON DELETE CASCADE;

-- ATTENDANCE foreign keys
ALTER TABLE ATTENDANCE
    ADD CONSTRAINT fk_attendance_employee 
    FOREIGN KEY (employee_id) 
    REFERENCES EMPLOYEE(employee_id)
    ON DELETE CASCADE;

-- LEAVE foreign keys
ALTER TABLE LEAVE
    ADD CONSTRAINT fk_leave_employee 
    FOREIGN KEY (employee_id) 
    REFERENCES EMPLOYEE(employee_id)
    ON DELETE CASCADE;

ALTER TABLE LEAVE
    ADD CONSTRAINT fk_leave_type 
    FOREIGN KEY (leave_type_id) 
    REFERENCES LEAVE_TYPE(leave_type_id)
    ON DELETE CASCADE;

ALTER TABLE LEAVE
    ADD CONSTRAINT fk_leave_approved_by 
    FOREIGN KEY (approved_by) 
    REFERENCES EMPLOYEE(employee_id)
    ON DELETE SET NULL;

-- PERFORMANCE_EVALUATION foreign keys
ALTER TABLE PERFORMANCE_EVALUATION
    ADD CONSTRAINT fk_eval_employee 
    FOREIGN KEY (employee_id) 
    REFERENCES EMPLOYEE(employee_id)
    ON DELETE CASCADE;

ALTER TABLE PERFORMANCE_EVALUATION
    ADD CONSTRAINT fk_eval_evaluator 
    FOREIGN KEY (evaluator_id) 
    REFERENCES EMPLOYEE(employee_id)
    ON DELETE CASCADE;

-- PAYROLL foreign keys
ALTER TABLE PAYROLL
    ADD CONSTRAINT fk_payroll_employee 
    FOREIGN KEY (employee_id) 
    REFERENCES EMPLOYEE(employee_id)
    ON DELETE CASCADE;

-- =================================================================
-- INDEXES FOR PERFORMANCE OPTIMIZATION
-- =================================================================

-- Employee indexes
CREATE INDEX idx_emp_department ON EMPLOYEE(department_id);
CREATE INDEX idx_emp_position ON EMPLOYEE(position_id);
CREATE INDEX idx_emp_supervisor ON EMPLOYEE(supervisor_id);
CREATE INDEX idx_emp_email ON EMPLOYEE(email);
CREATE INDEX idx_emp_status ON EMPLOYEE(status);
CREATE INDEX idx_emp_type ON EMPLOYEE(employment_type);
CREATE INDEX idx_emp_hire_date ON EMPLOYEE(hire_date);

-- Department indexes
CREATE INDEX idx_dept_manager ON DEPARTMENT(manager_id);

-- Employee Qualification indexes
CREATE INDEX idx_emp_qual_employee ON EMPLOYEE_QUALIFICATION(employee_id);
CREATE INDEX idx_emp_qual_qualification ON EMPLOYEE_QUALIFICATION(qualification_id);

-- Attendance indexes
CREATE INDEX idx_attendance_employee ON ATTENDANCE(employee_id);
CREATE INDEX idx_attendance_date ON ATTENDANCE(attendance_date);

-- Leave indexes
CREATE INDEX idx_leave_employee ON LEAVE(employee_id);
CREATE INDEX idx_leave_type ON LEAVE(leave_type_id);
CREATE INDEX idx_leave_status ON LEAVE(leave_status);
CREATE INDEX idx_leave_approved_by ON LEAVE(approved_by);
CREATE INDEX idx_leave_start_date ON LEAVE(start_date);

-- Performance Evaluation indexes
CREATE INDEX idx_eval_employee ON PERFORMANCE_EVALUATION(employee_id);
CREATE INDEX idx_eval_evaluator ON PERFORMANCE_EVALUATION(evaluator_id);
CREATE INDEX idx_eval_date ON PERFORMANCE_EVALUATION(evaluation_date);
CREATE INDEX idx_eval_status ON PERFORMANCE_EVALUATION(status);

-- Payroll indexes
CREATE INDEX idx_payroll_employee ON PAYROLL(employee_id);
CREATE INDEX idx_payroll_pay_period ON PAYROLL(pay_period_start, pay_period_end);
CREATE INDEX idx_payroll_payment_date ON PAYROLL(payment_date);

-- =================================================================
-- SEQUENCES (Optional - for manual ID generation if needed)
-- =================================================================
-- Note: IDENTITY columns automatically create sequences, but you can
-- create custom sequences if needed for specific requirements

-- =================================================================
-- COMPLETION MESSAGE
-- =================================================================
BEGIN
    DBMS_OUTPUT.PUT_LINE('=================================================================');
    DBMS_OUTPUT.PUT_LINE('HRIS Database Schema Created Successfully!');
    DBMS_OUTPUT.PUT_LINE('=================================================================');
    DBMS_OUTPUT.PUT_LINE('Tables Created: 12');
    DBMS_OUTPUT.PUT_LINE('  1. DEPARTMENT');
    DBMS_OUTPUT.PUT_LINE('  2. POSITION');
    DBMS_OUTPUT.PUT_LINE('  3. EMPLOYEE (Supertype)');
    DBMS_OUTPUT.PUT_LINE('  4. CONTRACT_EMPLOYEE (Subtype)');
    DBMS_OUTPUT.PUT_LINE('  5. PERMANENT_EMPLOYEE (Subtype)');
    DBMS_OUTPUT.PUT_LINE('  6. QUALIFICATION');
    DBMS_OUTPUT.PUT_LINE('  7. EMPLOYEE_QUALIFICATION (Bridge Table)');
    DBMS_OUTPUT.PUT_LINE('  8. ATTENDANCE');
    DBMS_OUTPUT.PUT_LINE('  9. LEAVE_TYPE');
    DBMS_OUTPUT.PUT_LINE(' 10. LEAVE');
    DBMS_OUTPUT.PUT_LINE(' 11. PERFORMANCE_EVALUATION');
    DBMS_OUTPUT.PUT_LINE(' 12. PAYROLL');
    DBMS_OUTPUT.PUT_LINE('=================================================================');
    DBMS_OUTPUT.PUT_LINE('Foreign Keys: 15');
    DBMS_OUTPUT.PUT_LINE('Indexes: 24');
    DBMS_OUTPUT.PUT_LINE('=================================================================');
END;
/

-- Enable DBMS_OUTPUT to see messages
SET SERVEROUTPUT ON;

-- Verify tables were created
SELECT table_name FROM user_tables ORDER BY table_name;

-- Verify constraints
SELECT constraint_name, constraint_type, table_name 
FROM user_constraints 
WHERE table_name IN ('DEPARTMENT', 'POSITION', 'EMPLOYEE', 'CONTRACT_EMPLOYEE', 
                     'PERMANENT_EMPLOYEE', 'QUALIFICATION', 'EMPLOYEE_QUALIFICATION', 
                     'ATTENDANCE', 'LEAVE_TYPE', 'LEAVE', 'PERFORMANCE_EVALUATION', 'PAYROLL')
ORDER BY table_name, constraint_type;
